---
driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart work

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
  - name: centos73
    driver:
      image: centos:7.3.1611
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts net-tools
      forward:
        - 9080:80

verifier:
  name: inspec

suites:
  - name: create
    run_list:
      - recipe[test_nginx::default]
    verifier:
          inspec_tests:
            - test/smoke/default/default_test.rb

  - name: create
    run_list:
      - recipe[test_nginx::default]
      - recipe[test_nginx::create]
    verifier:
          inspec_tests:
            - test/smoke/default/create_test.rb

  - name: enable
    run_list:
      - recipe[test_nginx::default]
      - recipe[test_nginx::enable]
    verifier:
          inspec_tests:
            - test/smoke/default/enable_test.rb

  - name: disable
    run_list:
      - recipe[test_nginx::default]
      - recipe[test_nginx::enable]
      - recipe[test_nginx::disable]
    verifier:
          inspec_tests:
            - test/smoke/default/disable_test.rb

attributes:
